apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8.9-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 61613
          env: # Setting Environmental Variables
            - name: RABBITMQ_DEFAULT_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username
            - name: RABBITMQ_DEFAULT_PASS # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password
---
# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq  # DNS name
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq
    - port: 61613
      targetPort: 61613
      name: stomp
  selector: # mysql Pod Should contain same labels
    app: rabbitmq
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant