version: '3'
services:
  mysql:
    image: mysql:8.0.31
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: 'SAKILA'
    ports:
      - '3306:3306'
    volumes:
      - '../db/sakila-mysql.sql:/docker-entrypoint-initdb.d/sakila-mysql.sql'

  rabbitmq:
      hostname: localhost
      container_name: rabbitmq-container
      image: rabbitmq:3.9.26-management-alpine
      restart: always
      ports:
          - "5672:5672"
          - "5673:5673"
          - "15672:15672"
          - "61613:61613"
      environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
      volumes:
        - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"