version: '3'
services:
    mysql:
        image: mysql:8.0.31
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 256M
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: 'SAKILA'
        ports:
            - '3306:3306'
        volumes:
            - '../db/sakila-mysql.sql:/docker-entrypoint-initdb.d/sakila-mysql.sql'